---
- name: Setup Common Software (Docker and Java 17)
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: latest
      notify: start docker

    - name: Install Java 17
      yum:
        name: java-17-amazon-corretto-devel
        state: present

  handlers:
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

- name: Setup CI/CD Server (Jenkins and SonarQube)
  hosts: ci_cd_server
  become: yes
  tasks:
    - name: Install Jenkins
      yum:
        name: jenkins
        state: present
      notify: start jenkins

    # Ensure Docker is running before attempting to pull and run SonarQube
    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    # Explicitly pull the SonarQube Docker image
    - name: Pull SonarQube Docker image
      docker_image:
        name: sonarqube
        state: present
      register: sonarqube_image

    # Pull and run SonarQube Docker container without volume mappings
    - name: Pull and run SonarQube Docker container
      docker_container:
        name: sonarqube
        image: "{{ sonarqube_image.image }}"
        state: started
        published_ports:
          - "9000:9000"
        restart_policy: unless-stopped
      when: sonarqube_image is changed

  handlers:
    - name: start jenkins
      service:
        name: jenkins
        state: started
        enabled: yes
