---
- name: Install Jenkins and Docker and Java
  hosts: all
  become: true
  tasks:
    - name: Install Docker               # installing docker on the server
      yum:
        name: docker
        state: present

    - name: Start Docker Service        # start and enable docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Java                # installing java on the server
      yum:
        name: java-17
        state: present
      
    - name: Add Jenkins Repository
      yum_repository:
        name: jenkins
        description: Jenkins Official Repository
        baseurl: http://pkg.jenkins.io/redhat-stable
        gpgcheck: no   # Disabling GPG check for Jenkins
        state: present

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins Service
      service:
        name: jenkins
        state: started
        enabled: yes

- name: Pull and Run SonarQube on java-server
  hosts: java-server
  become: true
  tasks:
    - name: Pull SonarQube Docker image
      command: docker pull sonarqube:latest

    - name: Run SonarQube container
      command: docker run -d --name sonarqube -p 9000:9000 sonarqube:latest
