---
- name: Install Jenkins, Docker, and Java
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Java
      yum:
        name: java-17
        state: present

    - name: Add Jenkins Repository
      hosts: CI/CD-server
      yum_repository:
        name: jenkins
        description: Jenkins Official Repository
        baseurl: http://pkg.jenkins.io/redhat-stable
        gpgcheck: no
        state: present

    - name: Install and Start Jenkins
      hosts: CI/CD-server
      yum:
        name: jenkins
        state: present
      notify: Start Jenkins Service
      when: "'CI/CD-server' in group_names"

  handlers:
    - name: Start Jenkins Service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Pull SonarQube Docker image
      hosts: CI/CD-server
      docker_image:
        name: sonarqube
        tag: latest
        source: pull

    - name: Run SonarQube container
      hosts: CI/CD-server
      docker_container:
        name: sonarqube
        image: sonarqube:latest
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "9000:9000"
