---
- name: Install Jenkins and Docker and java
  hosts: all
  become: true
  tasks:
    - name: Install Docker               # installing docker on both servers
      yum:
        name: docker
        state: present

    - name: Start Docker Service        # start and enable docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Java                # installing java on both server (for jenkins and jenkins slave)
      yum:
        name: java-17
        state: present
      

    - name: Add Jenkins Repository
      hosts: CI/CD-server
      yum_repository:
        name: jenkins
        description: Jenkins Official Repository
        baseurl: http://pkg.jenkins.io/redhat-stable
        gpgcheck: no   # Disabling GPG check for Jenkins
        state: present       # Only add Jenkins repository on 'CI/CD-server' hosts

    - name: Install Jenkins
      hosts: CI/CD-server
      yum:
        name: jenkins
        state: present
      when: "'CI/CD-server' in group_names"        # Only install Jenkins on 'CI/CD-server' hosts

    - name: Start Jenkins Service
      hosts: CI/CD-server
      service:
        name: jenkins
        state: started
        enabled: yes
              # Only start Jenkins service on 'CI/CD-server' hosts

    - name: Pull SonarQube Docker image
      hosts: CI/CD-server
      command: docker pull sonarqube:latest
             # Only execute this task on 'CI/CD-server' hosts

    - name: Run SonarQube container
      hosts: CI/CD-server
      command: docker run -d --name sonarqube -p 9000:9000 sonarqube:latest
            # Only execute this task on 'CI/CD-server' hosts
