---
- name: Setup Common Software (Docker and Java 17)
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: latest
      notify: start docker

    - name: Install Java 17
      yum:
        name: java-17-amazon-corretto-devel
        state: present

  handlers:
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

- name: Setup CI/CD Server (Jenkins and SonarQube)
  hosts: ci_cd_server
  become: yes
  tasks:
    - name: Install Jenkins
      yum:
        name: jenkins
        state: present
      notify: start jenkins

    - name: Pull and run SonarQube Docker container
      docker_container:
        name: sonarqube
        image: sonarqube
        state: started
        published_ports:
          - "9000:9000"
        restart_policy: unless-stopped
        volumes:
          - sonarqube_data:/opt/sonarqube/data
          - sonarqube_extensions:/opt/sonarqube/extensions
          - sonarqube_logs:/opt/sonarqube/logs

  handlers:
    - name: start jenkins
      service:
        name: jenkins
        state: started
        enabled: yes
