---
- hosts: all
  become: true

  pre_tasks:
    - name: Update package lists
      apt: update_cache=yes

  roles:
    - role: common
      # Define tasks for installing docker and java-17
    - role: jenkins
      # Define tasks for installing and configuring jenkins (CI/CD-server only)
    - role: sonarqube
      # Define tasks for pulling and running sonarqube image (CI/CD-server only)

  tasks:
    - name: Include conditional tasks based on server role
      include_tasks: "{{ lookup('file', '/etc/hostname') }}.yml"

...

# roles/common/main.yml
---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Install Java 17
  apt:
    name: openjdk-17-jdk
    state: present

...

# roles/jenkins/main.yml (CI/CD-server only)
---
- name: Add Jenkins repository key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: Add Jenkins repository list
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Start Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes

...

# roles/sonarqube/main.yml (CI/CD-server only)
---
- name: Pull Sonarqube docker image
  docker_pull:
    name: sonarqube:latest

- name: Run Sonarqube container
  docker_container:
    name: sonarqube
    image: sonarqube:latest
    ports:
      - "9000:9000"
    state: started

...

# CI/CD-server.yml
---
# This file is empty, as tasks are already included in jenkins and sonarqube roles
...

# Production-server.yml
---
# This file is empty, as no tasks are needed for this server
