---
- name: Setup Common Software (Docker and Java 17)
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: latest
      notify: start docker

    - name: Install Java 17
      yum:
        name: java-17
        state: present

    - name: Ensure Docker SDK for Python is installed
      pip:
        name: docker

  handlers:
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

- name: Setup CI/CD Server (Jenkins and SonarQube)
  hosts: ci_cd_server
  become: yes
  tasks:
    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins repo
        baseurl: https://pkg.jenkins.io/redhat-stable/
        gpgcheck: no  # Consider enabling GPG check if you have the appropriate key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present
      notify: start jenkins

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull SonarQube Docker image
      docker_image:
        name: sonarqube
        tag: latest
        source: pull

    - name: Run SonarQube Docker container
      docker_container:
        name: sonarqube
        image: sonarqube:latest
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "9000:9000"

  handlers:
    - name: start jenkins
      service:
        name: jenkins
        state: started
        enabled: yes
